name: ShivVerse-Auto-Upload
on:
  schedule:
    - cron: '30 3 * * *' # 🕘 Daily 9:00 AM IST (3:30 AM UTC)
  workflow_dispatch: # Manual Button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install google-api-python-client google-auth requests
      - name: Run Bot
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          POSTIMAGE_API_KEY: ${{ secrets.POSTIMAGE_API_KEY }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          FREEIMAGE_API_KEY: ${{ secrets.FREEIMAGE_API_KEY }}
          SUPABASE_URL_1: ${{ secrets.SUPABASE_URL_1 }}
          SUPABASE_KEY_1: ${{ secrets.SUPABASE_KEY_1 }}
          SUPABASE_URL_2: ${{ secrets.SUPABASE_URL_2 }}
          SUPABASE_KEY_2: ${{ secrets.SUPABASE_KEY_2 }}
        run: python bot.py
